### ISSUE TITLE
Make IAmRoot cross-platform

### ISSUE THREAD

**Issue by augustoproiete** [augustoproiete/i-am-root-nuget-package#1]
We're using [`CodeTaskFactory`](https://github.com/augustoproiete/i-am-root-nuget-package/blob/af4ee050130fecd93ee79afe43ec156c6b859b58/src/IAmRoot.targets#L4) at the moment, which only runs on Windows.

Some possible options:
- Update build .targets to use [`RoslynCodeTaskFactory`](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2019)
- Create a custom MSBuild task targeting .NET Standard 2.0
- (other?)

**Comment by 0xced** [comment]
I just tried IAmRoot on macOS and indeed got an error:

>   IAmRoot.targets(37, 3): [MSB4801] The task factory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild.
  IAmRoot.targets(37, 3): [MSB4175] The task factory "CodeTaskFactory" could not be loaded from the assembly "/usr/local/share/dotnet/sdk/5.0.102/Microsoft.Build.Tasks.Core.dll". The task factory must return a value for the "TaskType" property.

I edited the `IAmRoot.targets` file in place and changing `CodeTaskFactory` to `RoslynCodeTaskFactory` was enough to get the image open in my browser, so there's no need to create a custom MSBuild task.

**Comment by augustoproiete** [comment]
Thanks Cédric. That might indeed be the fastest route for a vNext just to get the ball rolling.

The main reason I thought an MSBuild Task could be a good idea is because `RoslynCodeTaskFactory` requires Visual Studio 2017 v15.8 or higher, and would allow this package to continue to work on older versions of VS, and machines with .NET 4.5, etc. I was planning to multi-target an MSBuild task for `netstandard2.0` and `net45`, and decide which one to use based on the version of VS detected in the .targets file.

But as you pointed out, switching from `CodeTaskFactory` to `RoslynCodeTaskFactory` is so simple that it's hard to argue that support for < VS2017 15.8 is more important than being cross-platform. :thinking:
